apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: hpa
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.86
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

# needed for zeroDowtime and http readinessProbe to work properly
  