argocd app create longhorn \
  --repo longhorn \
  --helm-chart longhorn \
  --dest-server https://kubernetes.default.svc \
  --dest-namespace longhorn-system \
  --sync-policy automated \
  --values ./longhorn/longhorn-values.yaml

#sprawdzenie statusu aplikacji
argocd app get longhorn
kubectl get pods -n longhorn-system
kubectl get sc
