apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n
data:
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  N8N_HEALTH_CHECK_ENABLED: "true"
  N8N_LOG_LEVEL: "info"
  GENERIC_TIMEZONE: "Europe/Warsaw"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_PASSWORD: "TwojeHasloDB"
