apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-artifactory-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: "107.125.8"
    helm:
      values: |
        artifactory:
          persistence:
            type: pvc
            storageClass: longhorn
            size: 10Gi
          replicas: 2

        postgresql:
          enabled: true
          persistence:
            storageClass: longhorn
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: jfrog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
