apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-artifactory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: "7.125.8"      # Zmieniono na istniejącą wersję
    helm:
      valueFiles:
        - values.yaml              # Wszystkie wartości poniżej powinny być w tym pliku
  destination:
    server: https://kubernetes.default.svc
    namespace: jfrog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
