artifactory:
  persistence:
    type: pvc
    storageClass: longhorn
    size: 10Gi      
  replicas: 2

postgresql:
  enabled: true
  persistence:
    storageClass: longhorn
    size: 5Gi       
  replicaCount: 1
  
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
  containerSecurityContext:
    capabilities:
      add:
        - IPC_LOCK
  podSecurityContext:
    runAsUser: 0
    fsGroup: 0

service:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.73