artifactory:
  persistence:
    type: pvc
    storageClass: longhorn
    size: 10Gi      #pwonno byc 20
  replicas: 2

postgresql:
  enabled: true
  persistence:
    storageClass: longhorn
    size: 5Gi       #powinno byc 10

nginx:
  replicaCount: 2

service:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.73