apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: test-app
data:
  DATABASE_HOST: my-db-service
  DATABASE_PORT: "3306"
  DATABASE_USER: root
  DATABASE_PASSWORD: mypassword
  DATABASE_NAME: mydatabase