apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-configma-deployment
  namespace: test-app
  labels:
    app: secret-configma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-configma-app
  template:
    metadata:
      labels: 
        app: secret-configma-app
    spec: 
      containers:
      - name: secret-configma-containerk 
        image: busybox
        command: ["sh", "-c", "printenv MYSQL_USER  MYSQL_PASSWORD DATABASE_HOST DATABASE_NAME DATABASE_USER DATABASE_PASSWORD; sleep 3600"]
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: password
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: DATABASE_PASSWORD  
