apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-configma-deployment
  namespace: test-app
  labels:
    app: secret-configma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-configma-app
  template:
    metadata:
      labels: 
        app: secret-configma-app
    spec: 
      containers:
      - name: secret-configma-containerk 
        image: busybox
        #command: ["sh", "-c", "printenv MYSQL_USER  MYSQL_PASSWORD DATABASE_HOST DATABASE_NAME DATABASE_USER DATABASE_PASSWORD; sleep 3600"]
        command: [ "/bin/sh", "-c", "env" ]
        envFrom:
        - secretRef:
            name: myapp-secret
        - configMapRef:
            name: myapp-config  
        