apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: test-app
data:
  mysql.conf: |
    [mysqld]
    port=3306
    socket=/temp/mysql.sock
    key_buffer_size=16M
    max_allowed_packet=128M
    