apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: test-app
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: busybox:1.28
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        command:
          - /bin/sh
          - -c
          - |
            while true; do
              cat /etc/myapp/mysql.conf
              cat /etc/myapp/secret.file
              sleep 30
            done
      - name: myapp-sidecar
        image: busybox:1.29 
        command:
          - /bin/sh
          - -c
          - |
            while true; do
              echo "Sidecar is running"
              sleep 60
            done            
        volumeMounts:
        - name: myapp-config
          mountPath: /etc/myapp/mysql.conf
          subPath: mysql.conf
        - name: myapp-secret
          mountPath: /etc/myapp/secret.file
          subPath: secret.file
          readOnly: true

      volumes:
      - name: myapp-config
        configMap:
          name: myapp-config
          items:
          - key: mysql.conf
            path: mysql.conf

      - name: myapp-secret
        secret:
          secretName: myapp-secret
          items:
          - key: secret.file
            path: secret.file
